<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260429223549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create POS entities without recreating existing user table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE customer_debt_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, phone VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE discount_beneficiary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, percentage INT NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) NOT NULL, price_cents INT NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE setting (id INT NOT NULL, shop_name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, tax_rate NUMERIC(5, 2) NOT NULL, enable_tax BOOLEAN NOT NULL, currency VARCHAR(10) NOT NULL, next_ticket_number INT NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payment_method VARCHAR(20) NOT NULL, paid BOOLEAN NOT NULL, subtotal_cents INT NOT NULL, discount_cents INT NOT NULL, total_cents INT NOT NULL, agent_id INT NOT NULL, discount_beneficiary_id INT DEFAULT NULL, debt_account_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F52993983414710B ON "order" (agent_id)');
        $this->addSql('CREATE INDEX IDX_F529939891607ED9 ON "order" (discount_beneficiary_id)');
        $this->addSql('CREATE INDEX IDX_F5299398CDAB0993 ON "order" (debt_account_id)');

        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price_cents INT NOT NULL, total_cents INT NOT NULL, order_ref_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F09E238517C ON order_item (order_ref_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F094584665A ON order_item (product_id)');

        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993983414710B FOREIGN KEY (agent_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F529939891607ED9 FOREIGN KEY (discount_beneficiary_id) REFERENCES discount_beneficiary (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398CDAB0993 FOREIGN KEY (debt_account_id) REFERENCES customer_debt_account (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09E238517C FOREIGN KEY (order_ref_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F094584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09E238517C');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F094584665A');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993983414710B');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F529939891607ED9');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398CDAB0993');

        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE discount_beneficiary');
        $this->addSql('DROP TABLE customer_debt_account');
    }
}
